### ISSUE TITLE
使用该主题后在集市页面显示不正常？

### ISSUE THREAD

**Issue by zrc951205** [Crowds21/Cliff-Dark#5]
思源1.8.2版本，集市点击主题后主题选项依然存在并遮挡内容
![image](https://user-images.githubusercontent.com/33946632/154014367-b5ed0a44-6368-4b2e-a6d3-446cb588525f.png)

**Comment by Crowds21** [comment]
感谢反馈,之后我调整一下

**Comment by Crowds21** [comment]
改动比较多,PDF 部分可能还存在问题,暂时先不推送到集市.
后面抽空改完 PDF 再推送.

**Comment by Crowds21** [comment]
> 思源1.8.2版本，集市点击主题后主题选项依然存在并遮挡内容

已经推送集市.等待D大审核.
